spring.application.name=banking-app
#Format - <how connecting jdbc here>:<which database>://<host>:<port>/<database_name>
spring.datasource.url=jdbc:mysql://localhost:3306/banking_app
spring.datasource.username=root
spring.datasource.password=root123

#automatically creates tables in db like orm or something using jpa entities
spring.jpa.hibernate.ddl-auto=update